baseURL = "http://roysk9.github.io/test/"
languageCode = "ja"
title = "Yボタンがネギに見える"
contentDir = "post"
disableKinds = ["RSS", "sitemap"]
publishDir = "docs"  # この行を追加
theme = "ananke"  # この行を追加
[taxonomies]
tag = "tags"
